// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CourseListerExpansion allows custom methods to be added to
// CourseLister.
type CourseListerExpansion interface{}

// CourseNamespaceListerExpansion allows custom methods to be added to
// CourseNamespaceLister.
type CourseNamespaceListerExpansion interface{}
