// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	coursecontrollerv1alpha1 "github.com/nchc-ai/course-crd/pkg/apis/coursecontroller/v1alpha1"
	versioned "github.com/nchc-ai/course-crd/pkg/client/clientset/versioned"
	internalinterfaces "github.com/nchc-ai/course-crd/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/nchc-ai/course-crd/pkg/client/listers/coursecontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CourseInformer provides access to a shared informer and lister for
// Courses.
type CourseInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CourseLister
}

type courseInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCourseInformer constructs a new informer for Course type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCourseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCourseInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCourseInformer constructs a new informer for Course type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCourseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NchcV1alpha1().Courses(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NchcV1alpha1().Courses(namespace).Watch(context.TODO(), options)
			},
		},
		&coursecontrollerv1alpha1.Course{},
		resyncPeriod,
		indexers,
	)
}

func (f *courseInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCourseInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *courseInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&coursecontrollerv1alpha1.Course{}, f.defaultInformer)
}

func (f *courseInformer) Lister() v1alpha1.CourseLister {
	return v1alpha1.NewCourseLister(f.Informer().GetIndexer())
}
