// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/nchc-ai/course-crd/pkg/client/clientset/versioned/typed/coursecontroller/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeNchcV1alpha1 struct {
	*testing.Fake
}

func (c *FakeNchcV1alpha1) Courses(namespace string) v1alpha1.CourseInterface {
	return &FakeCourses{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeNchcV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
